# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-15 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='game',
        ),
    ]
