# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180316_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='teacher',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
